/**
 * Global type aliases and shared interfaces for CampusOS.
 *
 * Feature-specific types live in features/[feature]/types.ts.
 * Database-generated types live in types/database.ts (generated by Supabase CLI).
 */

// ── Utility types ─────────────────────────────────────────────────────────────

/** Makes selected keys of T required */
export type RequireKeys<T, K extends keyof T> = T & Required<Pick<T, K>>;

/** Makes selected keys of T optional */
export type PartialKeys<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

/** Recursive partial */
export type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P];
};

// ── Academic domain enums ─────────────────────────────────────────────────────

export type TaskPriority = "low" | "medium" | "high" | "urgent";
export type TaskStatus = "todo" | "in_progress" | "done";
export type TaskType = "assignment" | "exam" | "project" | "reading" | "other";

export type SubjectType = "theory" | "lab" | "elective";
export type ClassType = "lecture" | "lab" | "tutorial";
export type DayOfWeek = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type AttendanceStatus = "present" | "absent" | "cancelled" | "holiday";

// ── UI state types ────────────────────────────────────────────────────────────

export type Theme = "light" | "dark" | "system";

export interface NavItem {
  label: string;
  href: string;
  icon: React.ComponentType<{ className?: string }>;
  badge?: number;
}

// ── API / Response types ──────────────────────────────────────────────────────

export interface ApiError {
  type: "ValidationError" | "AuthError" | "DatabaseError" | "NetworkError" | "AIError";
  message: string;
  code?: string;
}

export type ApiResult<T> =
  | { data: T; error: null }
  | { data: null; error: ApiError };

// ── Component prop types ──────────────────────────────────────────────────────

/** Standard children prop */
export interface WithChildren {
  children: React.ReactNode;
}

/** Standard className prop */
export interface WithClassName {
  className?: string;
}
